export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_DELETE_USER_REQUEST = 'FETCH_DELETE_USER_REQUEST';
export const FETCH_DELETE_USER_SUCCESS = 'FETCH_DELETE_USER_SUCCESS';
export const FETCH_DELETE_USER_FAILURE = 'FETCH_DELETE_USER_FAILURE';

export const FETCH_UPDATE_USER_REQUEST = 'FETCH_UPDATE_USER_REQUEST';
export const FETCH_UPDATE_USER_SUCCESS = 'FETCH_UPDATE_USER_SUCCESS';
export const FETCH_UPDATE_USER_FAILURE = 'FETCH_UPDATE_USER_FAILURE';
