export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'

export const RESET_LOGIN_STORE = 'RESET_LOGIN_STORE'
export const RESET_LOGIN_STORE_SUCCESS = 'RESET_LOGIN_STORE_SUCCESS'
export const RESET_LOGIN_STORE_FAILURE = 'RESET_LOGIN_STORE_FAILURE'
